# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Remix App Test - Ramiro"
client_id = "a8061edd481ce603162334fbb310b14b"
application_url = "https://rec-featuring-measurements-potatoes.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://rec-featuring-measurements-potatoes.trycloudflare.com/auth/callback",
  "https://rec-featuring-measurements-potatoes.trycloudflare.com/auth/shopify/callback",
  "https://rec-featuring-measurements-potatoes.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "proficient-testing-2-0.myshopify.com"
